#!/usr/bin/env bash

export MY_DIR="/home/temp_user"
export OUTPUT_DIR="$MY_DIR/github-bert/bert/resources/results/samples"
export RESOURCE_DIR="$MY_DIR/github-bert/bert/resources"

export MODEL_DIR="/tmp/samples/WNLI"

TMP_FILE="/tmp/input.txt"

BENCHMARK_FILE="$RESOURCE_DIR/all_benchmarks.txt"

# job through each benchmark to extract their pronouns.txt and jobs.txt feature vectors
while IFS= read -r BENCHMARK
do
    BENCHMARK="WNLI"
    for i in {1..20}
    do
        cat "$MODEL_DIR/$BENCHMARK-$i/eval_results.txt" > "$OUTPUT_DIR/$BENCHMARK-$i.txt" 
    done
done < "$BENCHMARK_FILE"


