#!/usr/bin/env bash

#BERT_BASE_DIR="/home/temp_user/corpora/uncased_L-12_H-768_A-12"
BERT_BASE_DIR="/tmp/mrpc_output4"

root_dir="/home/temp_user/github-bert/bert/resources"
out_dir="$root_dir/mrpc_pronouns"
input="$root_dir/pronouns.txt" # change jobs.txt to pronouns.txt
while IFS= read -r line
do
  echo "$line"
  echo "$line" > "/tmp/input.txt"
  python3 ../extract_features.py \
    --input_file="/tmp/input.txt" \
    --output_file="$out_dir/$line.jsonl" \
    --vocab_file="$BERT_BASE_DIR/vocab.txt" \
    --bert_config_file="$BERT_BASE_DIR/bert_config.json" \
    --init_checkpoint="$BERT_BASE_DIR/bert_model.ckpt-343" \
    --layers=-1,-2,-3,-4 \
    --max_seq_length=128 \
    --batch_size=8
done < "$input"


